server:
  port: 8088

fiap:
  debug: false

springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:~/fiapcoolshoesdb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    show-sql: true