spring:
  datasource:
    url: jdbc:h2:~/fiapcoolshoesbatchdb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap

file:
  path: /Users/douglasgoncalves/filetodelete.txt    

input:
  file: cadastro_pessoa.csv  