server:
  port: 8088

fiap:
  debug: false

jwt:
  secret: fiapSecr3t
  expire: 5

springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:~/fiapcoolshoesdb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    show-sql: true
  # security:
  #   user:
  #     name: douglas
  #     password: senha
  #     roles: ADMIN  